### PR TITLE
Dockerized

### PR DESCRIPTION
**Pull request by centsent**
This PR include two commits, one for dockerized, and the other one fix the `authenticationDatabase` problem.

## Dockerized

With docker, you do not need to install `go`  and `mongodb` on your local machine, it's easy to setup development environment for this repository.

### Prerequisites

Make sure you already installed below programs on your local machine:

* `git`
* `docker`
* `docker-compose`

### Usage

Just run `make test`, it will build the docker container and run `go test`.

### dep

[dep](https://github.com/golang/dep) is a prototype dependency management tool for Go.
To use `dep` in the container, prefix `make` for all `dep` commands, for example:

```bash
$ make dep "ensure -add github.com/some/repos"
```

Beware that the double quotes are required after `make dep` command.

## Authentication problem (Optional)

According to [mgo DialInfo documents](https://godoc.org/labix.org/v2/mgo#DialInfo),  the option `Source` is the database used to establish credentials and privileges with a MongoDB server. Defaults to the value of `Database`, if that is set, or "admin" otherwise.
Because we set the `Database` option in `Config` Object, so the `authenticationDatabase` argument was set to `mongodm_test` that could not connect to mongodb server correctly. 
The second commit solved this problem, it's optional to merge, but I think it's better to fully support options of `DialInfo`.

### CODE REVIEW

**Comment by moehlone** [comment]
LGTM! Thank you - I really like the approach with dep. 
This weekend I will adjust the readme and contribution file within this pull request and then we are fine. Afterwards I would continue with automatically CI testing and I think the license should change to MIT.

**Comment by moehlone** [comment]
Haven`t forgotten this. Just zero time, sorry!

**Comment by uzarubin** [comment]
I would strongly encourage using the alpine docker containers for testing. Not only would it make CI faster since it won't have to download a larger docker image...it would be faster for people to run the test suite locally.

**Comment by centsent** [comment]
Agree. Sorry I won't summit another commit to this PR, the latest `Dockerfile` as below, please review it, it works for me.

```Dockerfile
FROM alpine

ENV GOPATH /go
ENV PATH $PATH:$GOROOT/bin:$GOPATH/bin
ENV APP_DIR $GOPATH/src/mongodm

RUN apk add --no-cache --update go git libc-dev && \
    mkdir -p $APP_DIR && \
    go get -u github.com/golang/dep/cmd/dep && \
    apk del git

ADD . $APP_DIR
WORKDIR $APP_DIR
```

image

**Comment by moehlone** [comment]
@centsent @uzarubin I moved this to #14 - see information there :)

**Pull request closed without merging**
