### PR TITLE
Dockerized + Testing with TravisCI

### PR DESCRIPTION
**Pull request by moehlone**
@centsent I doubled the PR because it was easier to append my changes - we have to get this done ;)

### CODE REVIEW

**Comment by moehlone** [comment]
@centsent I used the golang:alpine image, which is the same like using alpine and then installing go. Size and time spent was also the same - is this ok for you?

**Comment by moehlone** [comment]
I decided against the travis go environment and switched back using docker-compose in Travis because we would have to manage/define a mongodb service in multiple files. The pro argument would be, that we could test multiple versions of go for each test run. But lets start easy.. If anything is missing please reopen this or start a new PR :) Thanks!

**Comment by moehlone** [comment]
One more note: with support of custom DialInfo as config attribute, I renamed `Source` to `DatabaseSource` (#15). I created tag `1.1.2` before if you need the other spelling.

**Comment by centsent** [comment]
Well done, it's ok for me.

**Pull request merged**
